### ISSUE TITLE
Replace exif.js?

### ISSUE THREAD

**Issue by narenpublic** [digitalascetic/ngx-pica#30]
exif.js is no longer maintained and I encountered a js bug on exif.js line 741 because n is not declared.

Can you switch to ExifReader?

https://github.com/mattiasw/ExifReader

**Comment by MikeKovarik** [comment]
Hello.

I'm a developer of another library [exifr](https://github.com/MikeKovarik/exifr). It's small, fast, configurable (*so just a few core files can be used to extract the photo's orientation instead of using the whole library*), supports more formats (tiff, heic), has fixes for bugs known to be in exif-js, etc...

And I'd be happy to do a Pull Reqest swapping exif-js for exifr.

Thanks.

**Comment by edezacas** [comment]
@MikeKovarik Thanks for your comment, Of course, any contribution to improvement is welcome.

**Comment by edezacas** [comment]
We have just released version 8.0.3 which replaces exifjs with exifr.
